apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  labels:
    {{- include "hockeybot.labels" . | nindent 4 }}
type: Opaque
data:
  YAHOO_CLIENT_ID: {{ .Values.secrets.yahooClientId | b64enc | quote }}
  YAHOO_CLIENT_SECRET: {{ .Values.secrets.yahooClientSecret | b64enc | quote }}
