"""In-memory store for pending OAuth authentication flows.

A nonce is generated by the `authenticate` MCP tool and embedded in the
Yahoo OAuth login URL. When the callback fires it calls resolve(), which
unblocks confirm_authentication() polling via get_result().
"""

_results: dict[str, dict] = {}
_resolved: set[str] = set()
_created: set[str] = set()


def create(nonce: str) -> None:
    """Register a new pending auth flow."""
    _created.add(nonce)
    _resolved.discard(nonce)
    _results.pop(nonce, None)


def resolve(nonce: str, user: dict) -> None:
    """Called by the OAuth callback when authentication completes."""
    _results[nonce] = user
    _resolved.add(nonce)


def get_result(nonce: str) -> dict | None:
    """
    Returns the authenticated user dict if the flow is complete, else None.
    Cleans up state on first successful read.
    """
    if nonce not in _resolved:
        return None
    user = _results.pop(nonce, None)
    _resolved.discard(nonce)
    _created.discard(nonce)
    return user


def is_pending(nonce: str) -> bool:
    """True if this nonce was created but not yet resolved or consumed."""
    return nonce in _created and nonce not in _resolved
