"""Yahoo OAuth2 session wrapper — returns a valid session, refreshing token if needed."""

import os

from dotenv import load_dotenv
from yahoo_oauth import OAuth2

load_dotenv()

_oauth_session: OAuth2 | None = None


def get_yahoo_session() -> OAuth2:
    """
    Return a valid Yahoo OAuth2 session.

    Requires YAHOO_OAUTH_CREDS_FILE in .env pointing to a JSON credentials
    file generated by auth/setup_yahoo.py. Raises ToolError if token refresh
    fails (browser re-auth required).
    """
    global _oauth_session

    creds_path = os.environ.get("YAHOO_OAUTH_CREDS_FILE", "oauth2.json")

    if _oauth_session is None:
        if not os.path.exists(creds_path):
            raise RuntimeError(
                f"Yahoo credentials file not found at '{creds_path}'. "
                "Run: uv run python auth/setup_yahoo.py"
            )
        _oauth_session = OAuth2(None, None, from_file=creds_path)

    if not _oauth_session.token_is_valid():
        try:
            _oauth_session.refresh_access_token()
        except Exception as e:
            raise RuntimeError(
                f"Yahoo token refresh failed: {e}. "
                "Run: uv run python auth/setup_yahoo.py to re-authorize."
            ) from e

    return _oauth_session
